#!/usr/bin/env python3
"""Phase H local source/link/image qualification; never a device executor."""
from __future__ import annotations
import argparse
from configparser import ConfigParser
import hashlib
import json
from pathlib import Path
import re
from m9_first_migration import inspect_candidate

ROOT = Path(__file__).resolve().parent.parent
ENV = "env:esp12e_m9_4m2m_mount_probe"
HEADER = ROOT / "firmware/include/boot/M9ProbeManifest.h"


def manifest_header() -> str:
    manifest = json.loads((ROOT / "tools/m9_stage2_sources.json").read_text())
    seed = (json.dumps(manifest["blank_config"], sort_keys=True, indent=2) + "\n").encode()
    assert manifest["blank_config"] == {"api_token":"", "lcd_rotation":0,
                                         "wifi_password":"", "wifi_ssid":""}
    files = {"config.json":{"bytes_lf":len(seed), "sha256_lf":hashlib.sha256(seed).hexdigest()},
             **manifest["assets"]}
    assert len(files) == 24 and sum(x["bytes_lf"] for x in files.values()) < 200000
    lines = ["// SPDX-License-Identifier: GPL-3.0-or-later",
             "// Generated by tools/m9_mount_probe.py from reviewed m9_stage2_sources.json.",
             "// Public blank seed/payload pins only; never a raw-image SHA claim.",
             "#pragma once", "#include <Arduino.h>", "#include <cstdint>",
             "namespace M9ProbeManifest {",
             "struct Entry { char path[48]; uint32_t bytes; uint8_t sha256[32]; };",
             f"constexpr size_t FILE_COUNT = {len(files)};",
             f"constexpr size_t PAYLOAD_BYTES = {sum(x['bytes_lf'] for x in files.values())};",
             f"constexpr size_t CONFIG_BYTES = {len(seed)};",
             f"const char CONFIG_SEED[] PROGMEM = {json.dumps(seed.decode())};",
             "const Entry FILES[FILE_COUNT] PROGMEM = {"]
    for path, pin in sorted(files.items()):
        assert len(path) + 1 < 48
        digest = ", ".join(f"0x{b:02x}" for b in bytes.fromhex(pin["sha256_lf"]))
        lines.append(f'    {{"/{path}", {pin["bytes_lf"]}, {{{digest}}}}},')
    return "\n".join(lines + ["};", "static_assert(FILE_COUNT < 32, \"Inventory bitset overflow\");",
                              "} // namespace M9ProbeManifest", ""])


def source_gate(root: Path = ROOT) -> dict:
    from m9_fsless_gate import inspect_source
    inspect_source(root) # Exact original profile-0 startup/loop and RAM telemetry.
    ini = ConfigParser(interpolation=None)
    ini.read(root / "firmware/platformio.ini", encoding="utf-8")
    p = ini[ENV]
    assert ini["platformio"]["default_envs"] == "esp12e"
    assert p["extends"] == "env:esp12e_m9_4m2m"
    assert p["board_build.ldscript"] == "eagle.flash.4m2m.ld"
    assert p["board_build.filesystem"] == "littlefs"
    assert "-DSHINO_BOOT_PROFILE=2" in p["build_flags"]
    assert "-DSHINO_M9_MOUNT_PROBE=1" in p["build_flags"]
    assert ini["env:esp12e"]["platform"] == "espressif8266@4.2.1"
    assert "framework-arduinoespressif8266@3.30102.0" in ini["env:esp12e"]["platform_packages"]
    assert (root / "firmware/include/boot/M9ProbeManifest.h").read_text() == manifest_header()
    probe = (root / "firmware/src/boot/M9LittleFsMountProbe.cpp").read_text()
    assert probe.count("LittleFS.begin()") == 1
    assert "LittleFS.setConfig(LittleFSConfig(false))" in probe
    assert probe.index("LittleFS.setConfig(LittleFSConfig(false))") < probe.index("LittleFS.begin()")
    for bad in ("LittleFS.format(", "LittleFS.remove(", "LittleFS.rename(", "LittleFS.mkdir(",
                "LittleFS.rmdir(", "ConfigManager", "SecureStorage", "EEPROM", "WiFi.begin(",
                "Update.", "ESP.restart(", "flashWrite(", "flashEraseSector("):
        assert bad not in probe, bad
    assert re.findall(r'LittleFS\.open\([^\n]+,\s*"([^"]+)"\)',probe) == ["r"]
    for required in ("_lfs_cfg.prog = denyProg", "_lfs_cfg.erase = denyErase",
                     "mode != OM_DEFAULT || access != AM_READ", "bool format() override",
                     "LFS_ERR_IO", "file.isFile()", "file.size() != pin.bytes",
                     "memcmp_P(bytes, M9ProbeManifest::CONFIG_SEED", "result.attempted) return",
                     "exactInventory() && checkPayloads()", "ESP.getFlashChipRealSize() != 0x400000"):
        assert required in probe, required
    bridge = (root / "firmware/src/boot/FirstBootBridge.cpp").read_text()
    route = bridge.split('server.on("/api/v1/m9/fs-probe/status", HTTP_GET')[1].split("#endif")[0]
    assert "if (!requireAuth()) return;" in route and "requireBrowser" not in route
    assert "SHINO_ENABLE_HOME_LAN == 0 && SHINO_ENABLE_FACTORY_RESTORE == 0" in bridge
    gate = (root / "firmware/scripts/m9_mount_probe_gate.py").read_text()
    assert all(f'"{x}"' in gate for x in ("upload", "uploadfs", "buildfs", "erase"))
    return {"status":"PASS_OFFLINE_MOUNT_PROBE_SOURCE", "profile":2,
            "environment":ENV, "checked_file_count":24, "device_contacts":0,
            "physical_gate":"HOLD / NOT_RUN", "physical_authorization":False}


def core_gate(core: Path) -> dict:
    pins = json.loads((ROOT / "tools/m9_mount_probe_sources.json").read_text())
    for path, expected in pins.items():
        body = (core / path).read_bytes().replace(b"\r\n", b"\n")
        assert hashlib.sha256(body).hexdigest() == expected, f"Pinned Core source changed: {path}"
    return {"status":"PASS_PINNED_CORE_READ_ONLY_ADAPTER", "files_checked":len(pins)}


def build_gate(symbols: Path, candidate: Path) -> dict:
    text = symbols.read_text(encoding="utf-8-sig")
    for symbol, address in (("_FS_start",0x40400000),("_FS_end",0x405FA000),
                            ("_FS_block",8192),("_FS_page",256)):
        assert re.search(rf"(?mi)^{address:08x}\s+A\s+{symbol}$",text),symbol
    for forbidden in ("ConfigManager::", "SecureStorage::", "EEPROMClass::begin(",
                      "EEPROMClass::commit(", "HomeLan::", "FactoryRollback::upload(",
                      "FactoryRollback::complete(", "UpdaterClass::begin(",
                      "UpdaterClass::write(", "UpdaterClass::end("):
        assert forbidden not in text, forbidden
    for required in ("M9LittleFsMountProbe::begin()", "M9LittleFsMountProbe::json(",
                     "ReadOnlyImpl::denyProg(", "ReadOnlyImpl::denyErase(",
                     "FirstBootBridge::run()", "FslessMetrics::apply("):
        assert required in text, required
    report = inspect_candidate(candidate)
    assert report["sector_rounded_write_extent"] < 0x100000 < 0x200000
    report.update(status="PASS_OFFLINE_MOUNT_PROBE_LINKED_IMAGE", physical_gate="HOLD / NOT_RUN",
                  remaining_lower_arena_bytes=0x200000-report["sector_rounded_write_extent"],
                  application_ceiling_margin_bytes=0x100000-report["sector_rounded_write_extent"])
    return report


def future_packet() -> dict:
    return {"scope":"PRINT ONLY / NOT AUTHORIZED BY PHASE H", "physical_authorization":False,
            "application_target":0, "steps":[
                "Fresh same-unit full 4 MiB PRE-PROBE; private rollback authority verified",
                "Exact application hash/link/policy; retained FS frozen raw-image slice verified",
                '# NOT AUTHORIZED BY PHASE H: <PINNED_PYTHON> -m esptool --chip esp8266 --port "<PORT>" --baud 115200 --before no-reset --after no-reset-stub --connect-attempts 1 write-flash --flash-mode keep --flash-freq keep --flash-size keep --no-compress 0x000000 "<EXACT_PROBE_BIN>"',
                "Full POST-PROBE before boot: payload exact; rounded extent..0x1FFFFF equals PRE",
                "POST[0x200000:0x3FA000] == PRE[0x200000:0x3FA000] == retained frozen FS",
                "POST[0x3FA000:0x400000] == PRE[0x3FA000:0x400000]",
                "Powered RTC 0/0 physically verified; GPIO0 release then existing RST",
                "Future mount/inventory/config/no-write/status/heap/180s/stale-recovery gates"],
            "internal_executor_retry_gate_required":True, "automatic_rollback":False,
            "normal_profile_mount_gate":"NOT_RUN", "normal_profile_runtime_gate":"NOT_RUN"}


def resources(sections: Path, stack: Path) -> dict:
    sizes={}
    for line in sections.read_text(encoding="utf-8-sig").splitlines():
        parts=line.split()
        if len(parts)==3 and parts[0].startswith('.') and parts[1].isdigit():
            sizes[parts[0]]=int(parts[1])
    ram=sum(sizes[x] for x in ('.data','.rodata','.bss'))
    flash=sum(sizes[x] for x in ('.data','.rodata','.text','.text1','.irom0.text'))
    assert ram + sizes['.noinit'] <= 40340 + 1024, 'Static RAM exceeds reviewed delta budget'
    frames={}
    for line in stack.read_text(encoding="utf-8-sig").splitlines():
        fields=line.split('\t')
        if len(fields)!=3: continue
        for name in ('checkPayloads()', 'M9LittleFsMountProbe::begin()', 'M9LittleFsMountProbe::json('):
            if name in fields[0]:frames[name]=int(fields[1])
    assert len(frames)==3 and max(frames.values())<=768, 'Unreviewed probe stack-frame growth'
    return {'static_ram_bytes':ram,'noinit_bytes':sizes['.noinit'],'linked_flash_bytes':flash,
            'static_ram_delta_vs_historical_stage1':ram-40340, 'probe_stack_frames_bytes':frames,
            'stack_call_chain_or_physical_high_water_proven':False,'stream_buffer_bytes':256,
            'status_buffer_bytes':768,'payload_bytes':181402}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate-manifest",action="store_true")
    parser.add_argument("--core-root",type=Path)
    parser.add_argument("--symbols",type=Path)
    parser.add_argument("--candidate",type=Path)
    parser.add_argument("--sections",type=Path)
    parser.add_argument("--stack-usage",type=Path)
    args = parser.parse_args()
    if args.generate_manifest: HEADER.write_text(manifest_header(),encoding="utf-8")
    if bool(args.symbols) != bool(args.candidate): parser.error("symbols/candidate required together")
    if bool(args.sections) != bool(args.stack_usage): parser.error("sections/stack-usage required together")
    report = source_gate()
    if args.core_root: report["core"] = core_gate(args.core_root)
    if args.symbols: report["build"] = build_gate(args.symbols,args.candidate)
    if args.sections: report["resources"] = resources(args.sections,args.stack_usage)
    report["future_packet"] = future_packet()
    print(json.dumps(report,indent=2,sort_keys=True))
    return 0

if __name__ == "__main__": raise SystemExit(main())
